- name: Copy kernel config
  copy:
    src: 50-ip-sec.conf
    dest: /etc/sysctl.d/50-ip-sec.conf
    owner: root
    group: root

- name: Apply kernel parameters
  ansible.builtin.shell: sysctl --system


