- name: Copy SSHD config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    validate: echo %s; /usr/sbin/sshd -t
  register: sshd_config

- name: Restart SSH service
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Copy fail2ban configuration
  copy:
    src: jail.conf
    dest: /etc/fail2ban/jail.conf
    owner: root
    group: root
  

- name: Copy fail2ban ssh configuration
  copy:
    src: ssh.conf
    dest: /etc/fail2ban/jail.d/ssh.conf
    owner: root
    group: root
  

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted
  
